name: Stop EC2 Instance

on:
  workflow_dispatch:

jobs:
  stop-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        run: printenv
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS-region: ap-south-1 # e.g., us-west-2
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 instance
        run: aws ec2 start-instances --instance-ids ${{ secrets.AWS_EC2_INSTANCE_ID }}
